### ISSUE TITLE
Bump IronBank Base Images

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1038]
### Describe what should be investigated or refactored
Node and Alpine images in IB are EOL. We need to update them

![image](https://github.com/user-attachments/assets/c90f5c86-c5d5-45d8-a62d-c5dd9c656043)

### Links to any relevant code
(optional) i.e. - https://github.com/defenseunicorns/pepr/blob/24f1f253b1db4c9d97717c0282b8f39c74d3ace1/README.md?plain=1#L3

### Additional context
Add any other context or screenshots about the technical debt here.

**Comment by cmwylie19** [comment]
![image](https://github.com/user-attachments/assets/5498d04d-5f56-4006-969d-70a1cb6d0465)

**Comment by btlghrants** [comment]
![image](https://github.com/user-attachments/assets/db420f90-1255-4607-800f-8fc408a6a3a4)

Alpine image has been updated & is now of most-current version available in IB (v3.20.2).

Looks like it's just the node version that needs poking now -- version will be updated: 20.16.0-slim --> 20.17.0-slim.

**Comment by btlghrants** [comment]
Turns out that I can't push to repo1 (cuz permissions of some kind) -- while we wait on the inquiry into that, I'm going to assign this back to @cmwylie19 .  I sent you over the patch of what I _wanted_ to push so lemme know if anything blows up on it & I can help dig in (since I can read, I just cant write).

Assuming permissions get worked out in the interim, I'll catch the next update, eh?
