### ISSUE TITLE
Unpublish or Deprecate `pepr:0.0.0-development` from NPM registry

### ISSUE THREAD

**Issue by samayer12** [defenseunicorns/pepr#1120]
### Environment
Device and OS: MacOS
App version: Local Development
Kubernetes distro being used: k3d
Other: N/A

### Steps to reproduce

```
npm run test:journey:build
npx --yes file:pepr-0.0.0-development.tgz init --skip-post-init
# Name module `pepr-test-module`
cd pepr-test-module 
npx --yes file:../pepr-0.0.0-development.tgz build
```

### Expected result

I can successfully run `npx ${PEPR_ALIAS} build` without errors as shown below.

### Actual Result

Module does not build.

### Visual Proof (screenshots, videos, text, etc)

* Working off of `main` on a5ae3cc35944b4b42182e3a44a48a9f0483710ed: [error.log](https://github.com/user-attachments/files/16935632/error.log)

### Severity/Priority

Medium

### Additional Context

`0.0.0-development` was accidentally published to the `npm` registry. As a result, one issue I ran into was working on a local development version of Pepr, which would build a new local artifact. However, running any pepr commands (e.g., `npx file:pepr-0.0.0-development.tgz build`) would _actually_ pull from `npm` and fail with an error. Since this is an opaque failure conditiona, this has added significant troubleshooting time to development.

NPM unpublishing [docs](https://docs.npmjs.com/unpublishing-packages-from-the-registry).

**Comment by btlghrants** [comment]
Just gave the un-pub a try -- since my NPM creds were working -- and it looks like NPMjs wants us to deprecate it instead (because it has dependents). :cry: 
![image](https://github.com/user-attachments/assets/434aa864-853e-4fcf-8fcd-75612e7a72b9)

IRT our troubleshooting collab today, I think a deprecation would've been enough to let us know something was wrong (cuz the `npm install` would have complained about us using a dep'd version).

...but now, as I go back to try & deprecate it, my NPM creds have dropped again. *sigh*

Next person in line (or future me if my creds come back): try to deprecate it!

**Comment by btlghrants** [comment]
Working with tech support to get my the NPM creds sorted right 'chnow. :crossed_fingers:

**Comment by btlghrants** [comment]
Alllllll righty -- was able to get the account creds all sorted.  NPMjs.com's `pepr@0.0.0-development` officially deprecated.

![image](https://github.com/user-attachments/assets/4e69d5a5-22f4-4ca9-9453-66dfd50aaabc)

**Comment by cmwylie19** [comment]
got it, looks good to close.
