### ISSUE TITLE
Add a uds run command to Pepr CI 

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1129]
### Is your feature request related to a problem? Please describe.

Before a release goes out, we want to be sure out latest image is not only passing e2e, unit, and soak tests, but nothing was introduced that will break uds core. 

### Describe the solution you'd like

- **Given** a PR is introduced that changes existing functionality
- **When** CI runs
- **Then** a uds run command occurs with the release candidate image and we know how it will affect uds core 

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by cmwylie19** [comment]
We will need a PR into UDS Core for this, deprioritizing until we do the[ PR into Core](https://github.com/defenseunicorns/uds-core/pull/761)

**Comment by btlghrants** [comment]
PR into core was accepted: https://github.com/defenseunicorns/uds-core/pull/766 . 🎉

**Comment by btlghrants** [comment]
Ugh, was testing if I could piece-meal merge a PR with multiple commits into main, a couple commits at a time, over time... but alas, I can't; when I merged the first increment of a linked PR it closed this issue & killed future action on that branch/PR (hence all the closed-open stuff in the history).

So instead, since I'm only touching a single Workflow file _and it has to be on the default branch in order to run_, I've gotten special dispensation from the rest of the team to bypass certain requirements (like using a PR) and will now just be working against main (as in, direct pushes (but only to that one file)) so that I can have a decent feedback cycle speed.

So... not gonna be any more linked PRs in this issue _but_ I'll do my best to keep commenting in here as appropriate.

**Comment by btlghrants** [comment]
Got a successful invocation of `uds run slim-dev` in GH, using custom pepr image, wee!

![image](https://github.com/user-attachments/assets/9a635f7b-c5f0-4d47-bb5f-a7ed9578104a)

**Comment by cmwylie19** [comment]
This is fixed with the UDS Smoke Test
