### ISSUE TITLE
dependabot should keep pepr version in excellent examples updated

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1139]
### Is your feature request related to a problem? Please describe.

Clashes can occur across versions in the excellent examples modules when there are different versions. We need the root `package.json` and the `package.json` of the modules.

### Describe the solution you'd like

- **Given** a new version of Pepr comes out
- **When** the dependabot for excellent-examples gives updates
- **Then** it updates the `package.json` and pertinent files in every module.

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by btlghrants** [comment]
Current state (of Dependabot in Pexex):
- Dependabot Alerts: enabled (but paused)
- Dependabot Securty Updates: enabled (but paused)
- Dependabot Version Updates: not enabled

Desired state:
- Dependabot Alerts: enabled (and _not_ paused)
- Dependabot Securty Updates: enabled (and _not_ paused)
- Dependabot Version Updates: enabled

Unknown:  whether / how Dependabot supports version updates across npm workspaces.  I think I'll start by taking this as a research task -- Dependabot docs, here I come!

**Comment by btlghrants** [comment]
Added a simple Dependabot config to the project, enabled it in settings, and got it to run.

Was able to see / approve / and merge a single Dependabot PR to update the `dependencies` of all of the example child project folders -- which only updated the `pepr` version since it's the only production dependency -- neat.

I also added the config necessary to update the `devDependencies` but... seeing the PR generated by Dependabot calls to mind some questions that I'll need to talk through with the team before I change the config and/or merge it.  Stuff like: should we pin the typescript version to the same version that the pepr `peerDependencies` uses?  Are there other deps that need to be called out / pinned / ignored?

**Comment by btlghrants** [comment]
Had a chat with the team today -- we decided _not_ to use dependabot to update the devDependencies.

New desired state:
- Dependabot Alerts: disabled
- Dependabot Securty Updates: disabled
- Dependabot Version Updates: enabled (but only for production dependencies)

Reason being: we don't really want "the most recent versions" of the devDeps, we want "the most recent versions that track what `pepr init` is producing" instead.  As a result, we're going to ignore updates to the dev group via dependabot & we're going to spin up a new story to cover the work necessary to design/implement that sync-and-update-sidechannel logic.

**Comment by cmwylie19** [comment]
Done! good job!
