### ISSUE TITLE
lifecycle of IsCreated() can be deceiving

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#237]
IsCreated() callbacks get called even if the object exists already. Trying to mutate it does not mutate it, and there's no feedback in the capability that the mutation "failed" or didn't happen. 

Repro steps:
1.  `kubectl create secret generic test-secret`
2.  create a capability that does this:

```
When(a.Secret)
  .IsCreated()
  .WithName("test-secret")
  .Mutate(secret => {
    Log.info("Validating secret", "test-pepr")
    secret.Raw.data["test-keyx"] === "test-value"
  });
```
3. `kubectl create secret generic test-secret`
`error: failed to create secret secrets "test-secret" already exists` <-- error
or via the API you get a 409

What's the right behavior for pepr here? options:
1. Ignore the callback if the object exists, and we're getting an IsCreated(). the control plan will provide the error
2. provide more information in the request object for Mutate() to let the application know if the object can be mutated or not (I don't love this).

**Comment by jeff-mccoy** [comment]
That's actually just how admission controllers always work, and why side-effects are risky if you wont manage them carefully. Notice this also hits the validation side. Below is an example of the mutation changing the name of the resource thereby preventing the API server validation error. Because this is possible, there's no reasonable way to stop it, it's by design.

<img width="643" alt="Screenshot 2023-09-07 at 12 19 36 AM" src="https://github.com/defenseunicorns/pepr/assets/882485/99db4f0d-dd7a-4f47-82c0-26922136adf2">

**Comment by jeff-mccoy** [comment]
And to be clear, the control plane is providing there error regardless, it just happens to happily pass through the admission controllers first before final validation by the API server.

**Comment by bburky** [comment]
Yeah, this makes sense as a result of doing this in an admission controller, this is also why I'd encourage the watch flow for side effect things. In watch you only observe things that are fully created. (However, in watch you have the issue that you probably want to implement "reconcile" logic, and you'll probably re-process all existing resources as "created" (or updated) during Pepr restarts.)
