### ISSUE TITLE
Look Into Allowing Regex in InNamespace

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/pepr#582]
### Is your feature request related to a problem? Please describe.
For uds-core policy exemptions, there might be a case for optionally locking down which namespace the operator watches for Exemption CRs. With the current implementation of `.InNamespace()`, it does not look to be possible to set it to a single namespace or list / all namespaces based on env var. (e.g. `.InNamespace(process.env.EXEMPTION_NS)`)

### Describe the solution you'd like

- Given an admin wants the option to allow single or all namespaces in `.InNamespace()`, or maybe namespaces that fit a pattern
- he or she could use a regex patterns like so `.InNamspace(".*")` , `.InNamespace("uds-policy-exemptions")`, `.InNamespace("*-policy-exemptions")`

### Describe alternatives you've considered
The alternative is to do this as the module author in the validator and not use `.InNamespace()`.

**Comment by jeff-mccoy** [comment]
I think we could add something for this, but it wouldn't work really for watch as that modifies a URL to the API server. We also support multiple (array) of namespaces.

**Comment by cmwylie19** [comment]
> I think we could add something for this, but it wouldn't work really for watch as that modifies a URL to the API server. We also support multiple (array) of namespaces.

Another thing to bring up is when the capability is for all namespaces:

```typescript
export const IstioVirtualService = new Capability({
  name: "istio-virtual-service",
  description: "Generate Istio VirtualService resources",
  namespaces: []
});
```

```typescript
When(a.Namespace)
.isCreatedOrUpdated()
.InNamespace("(.*)-system")
.Mutate(ns => ...)
```

When regex in the `Mutate` or `Validate`'s  `InNamespace` filter we are having to compare against all cluster namespaces which requires us to know all cluster namespaces which is incurs:
1. If we get the namespaces when the webhook is fired, which is the most accurate to ensure we have a comprehensive list of current namespaces. A time penalty against the [webhook timeout](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#timeouts) which will run before the module authors callback runs.
2. Additional RBAC for get or watch namespaces on Pepr's service account 

I suppose 1 could use a watch instead of a Get that could be programmed to get all namespaces in the cluster? Not sure, i would need to do more research.

@TristanHoladay - what are your thoughts on using the Array? Would that suffice or do you need the regex?

**Comment by cmwylie19** [comment]
closing this for now as there has been a workout set into place

**Comment by cmwylie19** [comment]
There is an ask for this, lets get it prioritized!
