### ISSUE TITLE
Pepr Watch is not Responding to Changes after 90 mins

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#745]
### Environment
Device and OS: UDS Core
App version: 
- UDS Core v0.19.0 (Pepr v0.29.0) Reported by Jordan
- UDS Core v0.18.0 Pepr 0.28.6 Reported by Wayne

Watch controller started responding after rolling. Only pod logs were health checks

Kubernetes distro being used:
Other: EKS Kubernetes 1.29

### Steps to reproduce
1. Working on reproducing [soak](https://github.com/cmwylie19/hello-pepr-soak/blob/main/README.md)

### Expected result
Upon disconnection, it reconnects

### Additional Context
Add any other context or screenshots about the technical debt here.

Well Known Bug:
https://github.com/kubernetes-client/csharp/issues/533
https://github.com/kubernetes-client/javascript/issues/596

**Comment by cmwylie19** [comment]
here is a temporary workaround that should force the watcher pod to reconnect. https://gist.github.com/cmwylie19/2c07e0e6f0962b8f18999488d1646a4a

**Comment by cmwylie19** [comment]
something with the AWS VPC CNI could have issues and is sometimes dropping policy. It _could_ have something to do with it. 

Related Issue - https://github.com/aws/amazon-vpc-cni-k8s/issues/2103

**Comment by cmwylie19** [comment]
Fixed by https://github.com/defenseunicorns/pepr/pull/766. If you experience this, use the environment variable `PEPR_RESYNCINTERVALSECONDS` and set it to something very low like 23 seconds. We soaked a module that was effected for 19 hours twice and did not see the problem

**Comment by marshall007** [comment]
Some seemingly related issues:
- https://github.com/kubernetes/kubernetes/issues/80313
- https://github.com/istio/istio/issues/8696
- https://github.com/istio/istio/issues/12187
- https://github.com/istio/istio/issues/12005
- https://github.com/istio/istio/issues/12121

Possible solution/workaround in https://github.com/istio/istio/issues/8696#issuecomment-792927519 by creating a `ServiceEntry` to treat connectino to k8s api-server as `MESH_EXTERNAL`.

**Comment by jeff-mccoy** [comment]
This is not technically resolved and setting a very low resync threshold like this is a really bad practice in production. Agree we either need to look at dropping Istio for this or looking at `MESH_EXTERNAL`

**Comment by cmwylie19** [comment]
This should be solved based on https://github.com/defenseunicorns/pepr/commit/c0d3aaac5ddab1321447e59c9ccd0cbe4a698da1 and the KFC informer pattern. All soak tests have passed

**Comment by joelmccoy** [comment]
Ran into this the other day using uds-core 0.26.1 (pepr v0.36.0) in our internal environments with `PEPR_LAST_SEEN_LIMIT_SECONDS` set to 60.  Didn't have the chance to catch the watch metrics, but will capture those if it occurs again.

**Comment by robsulllly** [comment]
Just ran through a UDS Core and bundling demo with Raytheon and ran into the problem where I had to restart the pepr-uds-core-watcher pod in order to get a successful deployment of mattermost, postgres operator, minio, etc. It looks like pepr blocks some of the secrets from being created, which then prevents mattermost from coming up.  Killing the pepr watcher pod and then re-doing the deployment fixes the problem.

This can happen regardless of whether the cluster/platform has been up for hours or just came up a couple minutes ago.  Does not happen every time though. 

UDS Core 0.27.2 - k3d-core-demo:0.27.2 (also existed on 0.26.1)
ARM64
[ghcr.io/defenseunicorns/packages/uds/dev-minio:0.0.2](http://ghcr.io/defenseunicorns/packages/uds/dev-minio:0.0.2)
[ghcr.io/defenseunicorns/packages/uds/postgres-operator:1.12.2-uds.2-upstream](http://ghcr.io/defenseunicorns/packages/uds/postgres-operator:1.12.2-uds.2-upstream)
[ghcr.io/defenseunicorns/packages/uds/mattermost:9.10.1-uds.0-upstream](http://ghcr.io/defenseunicorns/packages/uds/mattermost:9.10.1-uds.0-upstream)
Unfortunately, I was in the middle of a demo and had to press forward, kill the pepr watcher on the side, and re-deploy so I don't have the previous logs.

**Comment by JoeHCQ1** [comment]
Just got it today, happened while deploying core into a cluster, by the time I got to Neuvector, Pepr was AWOL. Had to kill the watcher, and bounce all affected Neuvector pods.

Core version 0.27.2.

**Comment by cmwylie19** [comment]
fixed in udici https://github.com/defenseunicorns/kubernetes-fluent-client/pull/399, we have not heard any more complaints. Feel free to open it back up if it occurs again.
