### ISSUE TITLE
node v22 has a punycode depre

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#811]
### Describe what should be investigated or refactored

On node v22 there is a deprecation warning for `punycode`.

```bash
(node:47514) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

**Definition of done:**
Remove the punycode warning

**Comment by schaeferka** [comment]
It looks like there isn't much that we can do besides keeping our dependency versions up to date and wait for them to be updated to remove `punycode`. 

There are a lot of issues on Github that have been raised around this deprecation warning, and it basically comes down to Node v22 deprecating `punycode` and module authors needing to update to a userland alternative. 

We aren't using `punycode` directly, our dependencies are using it. So our options appear to be:

- Stay with Node v20. The issue is not in v20.
- Keep our dependencies up to date and when they are updated to remove `punycode` the warning will go away and we will be able to use v22 with no warnings.
- Trace our dependency chain to find which modules are using `punycode` (or using dependencies that use `punycode`) and then change to alternative dependencies. It looks like the `tr46` module is the main offender in our dependency chain.

The first two options appear to be the best way to go.

**Comment by cmwylie19** [comment]
Thanks @schaeferka . Closing this for now
